### ISSUE TITLE
incorrect sca fix version being picked

### ISSUE THREAD

**Issue by r2c-david** [r2c-CSE/semgrep-utilities#84]
https://github.com/r2c-CSE/semgrep-utilities/blame/3d6d3cdd8e72c45576dd85014fd13c75207c09d8/integrations/gitlab/scaGitLabScript.py#L150

This function isn't comparing the semver of the dep across multiple fixes, resulting in the incorrect patch version sometimes being surfaced

**Comment by bandarisantosh** [comment]
Closing this issue in the lieu of https://github.com/r2c-CSE/semgrep-utilities/pull/86.
